### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by paciorek** [berkeley-scf/course-site-myst#11]
I put a CC-BY default license file in `course-site-quarto` with info in instructions about choosing a license and a link to license in footer of left sidebar.

Once we decide if that's what we want, we should copy into this repo to provide similar functionality.

**Comment by paciorek** [comment]
just bumping this as license is still lacking from `course-site-myst`.

**Comment by ryanlovett** [comment]
Fixed by 509bff7. This puts a small icon at the top of every page linking to the license. There's also a way to license the code, which I inserted as a comment. The example `myst.yml` contains a link to the frontmatter documentation which has a section on licensing, so I think that should be sufficient for people to find.

<img width="238" alt="Screenshot 2024-06-11 at 10 48 37 AM" src="https://github.com/berkeley-scf/course-site-myst/assets/10248125/ed02adbf-a367-4043-97f0-8234b603d336">
